<b>Numpy Tutorials</b><br>
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object,
and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists.
While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type.<br>
It's used for fasr process.  use less memory to store data. convenient<br>



In [1]:
## initially Lets import numpy


import numpy as np

In [2]:
one_d_array = np.array([1,2,3,4]) # create 1D array
print(one_d_array) # printing 1d array

[1 2 3 4]


In [3]:
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # create 1D array
print(two_d_array) #printing 2D array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
type(one_d_array)

numpy.ndarray

In [5]:
two_d_array.shape# (row,columns)

(3, 3)

In [6]:
two_d_array.size

9

In [7]:
two_d_array.ndim

2

In [8]:
one_d_array.dtype

dtype('int32')

In [9]:
np.ones((3,3), dtype = int)#same for zeros, also change the data type.

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
arr = np.arange(1,13,2) #also enter the steps.
#np.arrange(click shift+ enter ) for get details.
arr

array([ 1,  3,  5,  7,  9, 11])

In [11]:
#linspace() function - Return evenly spaced numbers over a specified interval.
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [12]:
arr_reshape = np.reshape(arr, (3,4)) #reshape by the name of arra and the size.
print(arr_reshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
#make 2d array
arr = np.arange(1,13).reshape(2,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [19]:
arr.ravel() #convert 2d array into one d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
a = arr1 + arr2 
#np.add(arr1,arr2)
#same for subtract, divide, multiply.
a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [26]:
arr1.dot(arr2)#dot product

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [31]:
arr1.max()#return maximum value same for min.
arr1.argmax()#Retuen index of maximum value.
arr1.max(axis = 1)

array([3, 6, 9])

In [32]:
np.sum(arr1)#sum of all he value of the ar

45

In [33]:
np.mean(arr1)

5.0

In [35]:
np.sqrt(arr1)
np.std(arr1)#find standard deviation

2.581988897471611

In [36]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [38]:
mp  = np.arange(1,101).reshape(10,10)
mp

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [39]:
mp[2,3]

24

In [40]:
mp[:,0]#for first columns

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [42]:
mp[0,]#for first row

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
mp[:]#mp[::], mp[:,:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [50]:
mp.dtype

dtype('int32')

In [54]:
arr3 = np.arange(1,17).reshape(4,4)
arr4 = np.arange(17,33).reshape(4,4)

In [60]:
#for concatinate 
np.concatenate((arr3,arr4)) #focus on braket it concatenate column wise


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [62]:
np.concatenate((arr3,arr4), axis  = 1) #do concatinate by row wise.

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [66]:
np.vstack((arr1,arr2))#same for hstack.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
np.split(arr3,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [70]:
np.sin(180)#this is in degree
np.sin(180  *np.pi/180)#give the value in radian


1.2246467991473532e-16

In [71]:
import random

In [73]:
np.random.random(1)#give value between zero to one

array([0.21008318])

In [75]:
np.random.random((3,3))

array([[0.03225922, 0.53810193, 0.86427037],
       [0.76696724, 0.68311196, 0.74499481],
       [0.48103236, 0.81158937, 0.8288916 ]])

In [78]:
np.random.randint(1,4,(2,4))#genate array by this size of this value.

array([[3, 1, 3, 2],
       [2, 1, 3, 2]])

In [80]:
x = [2,4,5,3]
np.random.choice(x)#choose random number.

5

In [83]:
na = "My name is Ujjwal Mittal"
go = "Im learn the python basics for practice"


In [89]:
np.char.add(na,go) #add 2 string
np.char.lower(na)#same for upper.
np.char.center(na,35, fillchar = "#")

array('######My name is Ujjwal Mittal#####', dtype='<U35')

In [90]:
np.char.split(na)

array(list(['My', 'name', 'is', 'Ujjwal', 'Mittal']), dtype=object)

In [91]:
np.char.replace(go, "learn","had learnt")

array('Im had learnt the python basics for practice', dtype='<U44')

In [92]:
np.char.find(na,"Ujjwal")

array(11)